packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  zod: '~4.3.6'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
