import { initTRPC } from '@trpc/server';

const t = initTRPC.create();

/**
 * AppRouter — auto-generated by nestjs-trpc from the `api` NestJS app.
 * This file will be regenerated when `apps/api` is built.
 * Do not edit manually.
 */
const appRouter = t.router({});
export type AppRouter = typeof appRouter;
